FROM grpc/python
ADD . /microservices-grpc-go-python
WORKDIR /microservices-grpc-go-python/discount
RUN pip install --upgrade pip \
 && pip install grpcio grpcio-tools
CMD ["python", "server.py", "11443"]
