# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ecommerce_pb2 as ecommerce__pb2


class DiscountStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ApplyDiscount = channel.unary_unary(
        '/ecommerce.Discount/ApplyDiscount',
        request_serializer=ecommerce__pb2.DiscountRequest.SerializeToString,
        response_deserializer=ecommerce__pb2.DiscountResponse.FromString,
        )


class DiscountServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ApplyDiscount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DiscountServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ApplyDiscount': grpc.unary_unary_rpc_method_handler(
          servicer.ApplyDiscount,
          request_deserializer=ecommerce__pb2.DiscountRequest.FromString,
          response_serializer=ecommerce__pb2.DiscountResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ecommerce.Discount', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
